# Site wide configuration

title: Tiven's Labs
locale: zh
description: personal technical blog about SAP.
logo: site-logo.png
search: true
url: http://labs.tiven.wang
cdnjs: http://cdnjs.tiven.wang/ajax/libs
home-url: http://tiven.wang

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style:    compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
#  - jekyll-archives

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..4
  enable_coderay: false
  syntax_highlighter: rouge

include: [".htaccess"]
exclude: ["config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# site disqus comments enable
comments: true
